import { esc, emptyState, pageHeader, uid } from '../components/helpers.js';
import { openFormModal } from '../components/modal.js';

export function renderObjectives(ctx) {
  const locked = ctx.session.isAct1Completed;
  document.getElementById('page').innerHTML = `
    ${pageHeader('Learning objectives', 'Turn knowledge gaps into specific research goals and link each goal to the relevant problem points.', `<button id="print-act1" class="button button-secondary">Print Act 1</button><button id="toggle-lock" class="button ${locked ? 'button-secondary' : 'button-success'}">${locked ? 'Unlock Act 1' : '✓ Mark Act 1 complete'}</button>`)}
    ${locked ? '<div class="lock-banner"><span>🔒</span><div><strong>Act 1 is complete and locked</strong><div class="small">Act 2 remains editable. Unlock only if the group agrees to revise its analysis.</div></div></div>' : ''}
    <section class="card"><div class="form-row"><input id="objective-input" class="input" placeholder="Write a specific learning objective…" ${locked ? 'disabled' : ''}><button id="add-objective" class="button button-primary" ${locked ? 'disabled' : ''}>＋ Add objective</button></div></section>
    <section class="card"><div class="list-stack">${ctx.session.objectives.length ? ctx.session.objectives.map((objective, index) => `<article class="objective-card"><div class="objective-head"><span class="code-badge">LO${index + 1}</span><div class="objective-text">${esc(objective.text)}</div><button class="button button-ghost" data-edit="${esc(objective.id)}" ${locked ? 'disabled' : ''}>✎</button><button class="button button-ghost" data-delete="${esc(objective.id)}" ${locked ? 'disabled' : ''}>🗑</button></div><div class="field-label mt-3">Linked problem points</div><div class="check-grid">${ctx.session.problems.length ? ctx.session.problems.map((problem, pIndex) => `<label class="check-chip"><input type="checkbox" data-link-lo="${esc(objective.id)}" value="${esc(problem.id)}" ${objective.linkedProblemIds.includes(problem.id) ? 'checked' : ''} ${locked ? 'disabled' : ''}> P${pIndex + 1} · ${esc(problem.text)}</label>`).join('') : '<span class="muted small">Add problem points before linking this objective.</span>'}</div></article>`).join('') : emptyState('▱', 'No learning objectives yet', 'Add a focused research goal based on the group’s knowledge gaps.')}</div></section>`;
  const add = () => { const input = document.getElementById('objective-input'); if (!input.value.trim()) return; ctx.setField('objectives', [...ctx.session.objectives, { id:uid('lo'), text:input.value.trim(), linkedProblemIds:[] }]); ctx.render(); };
  document.getElementById('add-objective').addEventListener('click', add);
  document.getElementById('objective-input').addEventListener('keydown', event => { if (event.key === 'Enter') add(); });
  document.querySelectorAll('[data-link-lo]').forEach(check => check.addEventListener('change', () => { const objective = ctx.session.objectives.find(item => item.id === check.dataset.linkLo); objective.linkedProblemIds = check.checked ? [...objective.linkedProblemIds, check.value] : objective.linkedProblemIds.filter(id => id !== check.value); ctx.setField('objectives', ctx.session.objectives); }));
  document.querySelectorAll('[data-edit]').forEach(button => button.addEventListener('click', () => { const objective = ctx.session.objectives.find(item => item.id === button.dataset.edit); openFormModal('Edit learning objective', [{ name:'text', label:'Learning objective', type:'textarea', value:esc(objective.text) }], ({ text }) => { objective.text = text.trim(); ctx.setField('objectives', ctx.session.objectives); ctx.render(); }); }));
  document.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => { ctx.setField('objectives', ctx.session.objectives.filter(item => item.id !== button.dataset.delete)); ctx.render(); }));
  document.getElementById('print-act1').addEventListener('click', () => ctx.API.openPrintWindow());
  document.getElementById('toggle-lock').addEventListener('click', () => { if (!locked && !confirm('Mark Act 1 complete and lock all Act 1 editing?')) return; if (locked && !confirm('Unlock Act 1 for revisions?')) return; ctx.setField('isAct1Completed', !locked); ctx.render(); });
}
